import type { Country } from './types'

export const COUNTRIES: Country[] = [
  { code: '0093', flag: 'https://flagcdn.com/af.svg', name: 'Afghanistan', dialCode: '+93' },
  { code: '0355', flag: 'https://flagcdn.com/al.svg', name: 'Albania', dialCode: '+355' },
  { code: '0213', flag: 'https://flagcdn.com/dz.svg', name: 'Algeria', dialCode: '+213' },
  { code: '1684', flag: 'https://flagcdn.com/as.svg', name: 'American Samoa', dialCode: '+1684' },
  { code: '0376', flag: 'https://flagcdn.com/ad.svg', name: 'Andorra', dialCode: '+376' },
  { code: '0244', flag: 'https://flagcdn.com/ao.svg', name: 'Angola', dialCode: '+244' },
  { code: '1264', flag: 'https://flagcdn.com/ai.svg', name: 'Anguilla', dialCode: '+1264' },
  { code: '1268', flag: 'https://flagcdn.com/ag.svg', name: 'Antigua and Barbuda', dialCode: '+1268' },
  { code: '0054', flag: 'https://flagcdn.com/ar.svg', name: 'Argentina', dialCode: '+54' },
  { code: '0374', flag: 'https://flagcdn.com/am.svg', name: 'Armenia', dialCode: '+374' },
  { code: '0297', flag: 'https://flagcdn.com/aw.svg', name: 'Aruba', dialCode: '+297' },
  { code: '0061', flag: 'https://flagcdn.com/au.svg', name: 'Australia', dialCode: '+61' },
  { code: '0043', flag: 'https://flagcdn.com/at.svg', name: 'Austria', dialCode: '+43' },
  { code: '0994', flag: 'https://flagcdn.com/az.svg', name: 'Azerbaijan', dialCode: '+994' },
  { code: '1242', flag: 'https://flagcdn.com/bs.svg', name: 'Bahamas', dialCode: '+1242' },
  { code: '0973', flag: 'https://flagcdn.com/bh.svg', name: 'Bahrain', dialCode: '+973' },
  { code: '0880', flag: 'https://flagcdn.com/bd.svg', name: 'Bangladesh', dialCode: '+880' },
  { code: '1246', flag: 'https://flagcdn.com/bb.svg', name: 'Barbados', dialCode: '+1246' },
  { code: '0375', flag: 'https://flagcdn.com/by.svg', name: 'Belarus', dialCode: '+375' },
  { code: '0032', flag: 'https://flagcdn.com/be.svg', name: 'Belgium', dialCode: '+32' },
  { code: '0501', flag: 'https://flagcdn.com/bz.svg', name: 'Belize', dialCode: '+501' },
  { code: '0229', flag: 'https://flagcdn.com/bj.svg', name: 'Benin', dialCode: '+229' },
  { code: '1441', flag: 'https://flagcdn.com/bm.svg', name: 'Bermuda', dialCode: '+1441' },
  { code: '0975', flag: 'https://flagcdn.com/bt.svg', name: 'Bhutan', dialCode: '+975' },
  { code: '0591', flag: 'https://flagcdn.com/bo.svg', name: 'Bolivia', dialCode: '+591' },
  { code: '0387', flag: 'https://flagcdn.com/ba.svg', name: 'Bosnia and Herzegovina', dialCode: '+387' },
  { code: '0267', flag: 'https://flagcdn.com/bw.svg', name: 'Botswana', dialCode: '+267' },
  { code: '0055', flag: 'https://flagcdn.com/br.svg', name: 'Brazil', dialCode: '+55' },
  { code: '0246', flag: 'https://flagcdn.com/io.svg', name: 'British Indian Ocean Territory', dialCode: '+246' },
  { code: '1284', flag: 'https://flagcdn.com/vg.svg', name: 'British Virgin Islands', dialCode: '+1284' },
  { code: '0673', flag: 'https://flagcdn.com/bn.svg', name: 'Brunei', dialCode: '+673' },
  { code: '0359', flag: 'https://flagcdn.com/bg.svg', name: 'Bulgaria', dialCode: '+359' },
  { code: '0226', flag: 'https://flagcdn.com/bf.svg', name: 'Burkina Faso', dialCode: '+226' },
  { code: '0257', flag: 'https://flagcdn.com/bi.svg', name: 'Burundi', dialCode: '+257' },
  { code: '0855', flag: 'https://flagcdn.com/kh.svg', name: 'Cambodia', dialCode: '+855' },
  { code: '0237', flag: 'https://flagcdn.com/cm.svg', name: 'Cameroon', dialCode: '+237' },
  { code: '0001', flag: 'https://flagcdn.com/ca.svg', name: 'Canada', dialCode: '+1' },
  { code: '0238', flag: 'https://flagcdn.com/cv.svg', name: 'Cape Verde', dialCode: '+238' },
  { code: '1345', flag: 'https://flagcdn.com/ky.svg', name: 'Cayman Islands', dialCode: '+1345' },
  { code: '0236', flag: 'https://flagcdn.com/cf.svg', name: 'Central African Republic', dialCode: '+236' },
  { code: '0235', flag: 'https://flagcdn.com/td.svg', name: 'Chad', dialCode: '+235' },
  { code: '0056', flag: 'https://flagcdn.com/cl.svg', name: 'Chile', dialCode: '+56' },
  { code: '0086', flag: 'https://flagcdn.com/cn.svg', name: 'China', dialCode: '+86' },
  { code: '0057', flag: 'https://flagcdn.com/co.svg', name: 'Colombia', dialCode: '+57' },
  { code: '0269', flag: 'https://flagcdn.com/km.svg', name: 'Comoros', dialCode: '+269' },

  { code: '0682', flag: 'https://flagcdn.com/ck.svg', name: 'Cook Islands', dialCode: '+682' },
  { code: '0506', flag: 'https://flagcdn.com/cr.svg', name: 'Costa Rica', dialCode: '+506' },
  { code: '0225', flag: 'https://flagcdn.com/ci.svg', name: 'Côte d\'Ivoire', dialCode: '+225' },
  { code: '0385', flag: 'https://flagcdn.com/hr.svg', name: 'Croatia', dialCode: '+385' },
  { code: '0053', flag: 'https://flagcdn.com/cu.svg', name: 'Cuba', dialCode: '+53' },
  { code: '0357', flag: 'https://flagcdn.com/cy.svg', name: 'Cyprus', dialCode: '+357' },
  { code: '0420', flag: 'https://flagcdn.com/cz.svg', name: 'Czech Republic', dialCode: '+420' },
  { code: '0045', flag: 'https://flagcdn.com/dk.svg', name: 'Denmark', dialCode: '+45' },
  { code: '0253', flag: 'https://flagcdn.com/dj.svg', name: 'Djibouti', dialCode: '+253' },
  { code: '1767', flag: 'https://flagcdn.com/dm.svg', name: 'Dominica', dialCode: '+1767' },
  { code: '1809', flag: 'https://flagcdn.com/do.svg', name: 'Dominican Republic', dialCode: '+1809' },
  { code: '0670', flag: 'https://flagcdn.com/tl.svg', name: 'East Timor', dialCode: '+670' },
  { code: '0593', flag: 'https://flagcdn.com/ec.svg', name: 'Ecuador', dialCode: '+593' },
  { code: '0020', flag: 'https://flagcdn.com/eg.svg', name: 'Egypt', dialCode: '+20' },
  { code: '0503', flag: 'https://flagcdn.com/sv.svg', name: 'El Salvador', dialCode: '+503' },
  { code: '0240', flag: 'https://flagcdn.com/gq.svg', name: 'Equatorial Guinea', dialCode: '+240' },
  { code: '0291', flag: 'https://flagcdn.com/er.svg', name: 'Eritrea', dialCode: '+291' },
  { code: '0372', flag: 'https://flagcdn.com/ee.svg', name: 'Estonia', dialCode: '+372' },
  { code: '0251', flag: 'https://flagcdn.com/et.svg', name: 'Ethiopia', dialCode: '+251' },
  { code: '0500', flag: 'https://flagcdn.com/fk.svg', name: 'Falkland Islands', dialCode: '+500' },
  { code: '0298', flag: 'https://flagcdn.com/fo.svg', name: 'Faroe Islands', dialCode: '+298' },
  { code: '0679', flag: 'https://flagcdn.com/fj.svg', name: 'Fiji', dialCode: '+679' },
  { code: '0358', flag: 'https://flagcdn.com/fi.svg', name: 'Finland', dialCode: '+358' },
  { code: '0033', flag: 'https://flagcdn.com/fr.svg', name: 'France', dialCode: '+33' },
  { code: '0594', flag: 'https://flagcdn.com/gf.svg', name: 'French Guiana', dialCode: '+594' },
  { code: '0689', flag: 'https://flagcdn.com/pf.svg', name: 'French Polynesia', dialCode: '+689' },
  { code: '0241', flag: 'https://flagcdn.com/ga.svg', name: 'Gabon', dialCode: '+241' },
  { code: '0220', flag: 'https://flagcdn.com/gm.svg', name: 'Gambia', dialCode: '+220' },
  { code: '0995', flag: 'https://flagcdn.com/ge.svg', name: 'Georgia', dialCode: '+995' },
  { code: '0049', flag: 'https://flagcdn.com/de.svg', name: 'Germany', dialCode: '+49' },
  { code: '0233', flag: 'https://flagcdn.com/gh.svg', name: 'Ghana', dialCode: '+233' },
  { code: '0350', flag: 'https://flagcdn.com/gi.svg', name: 'Gibraltar', dialCode: '+350' },
  { code: '0030', flag: 'https://flagcdn.com/gr.svg', name: 'Greece', dialCode: '+30' },
  { code: '0299', flag: 'https://flagcdn.com/gl.svg', name: 'Greenland', dialCode: '+299' },
  { code: '1473', flag: 'https://flagcdn.com/gd.svg', name: 'Grenada', dialCode: '+1473' },

  { code: '1671', flag: 'https://flagcdn.com/gu.svg', name: 'Guam', dialCode: '+1671' },
  { code: '0502', flag: 'https://flagcdn.com/gt.svg', name: 'Guatemala', dialCode: '+502' },
  { code: '0224', flag: 'https://flagcdn.com/gn.svg', name: 'Guinea', dialCode: '+224' },
  { code: '0245', flag: 'https://flagcdn.com/gw.svg', name: 'Guinea-Bissau', dialCode: '+245' },
  { code: '0592', flag: 'https://flagcdn.com/gy.svg', name: 'Guyana', dialCode: '+592' },
  { code: '0509', flag: 'https://flagcdn.com/ht.svg', name: 'Haiti', dialCode: '+509' },
  { code: '0504', flag: 'https://flagcdn.com/hn.svg', name: 'Honduras', dialCode: '+504' },
  { code: '0852', flag: 'https://flagcdn.com/hk.svg', name: 'Hong Kong', dialCode: '+852' },
  { code: '0036', flag: 'https://flagcdn.com/hu.svg', name: 'Hungary', dialCode: '+36' },
  { code: '0354', flag: 'https://flagcdn.com/is.svg', name: 'Iceland', dialCode: '+354' },
  { code: '0091', flag: 'https://flagcdn.com/in.svg', name: 'India', dialCode: '+91' },
  { code: '0062', flag: 'https://flagcdn.com/id.svg', name: 'Indonesia', dialCode: '+62' },
  { code: '0098', flag: 'https://flagcdn.com/ir.svg', name: 'Iran', dialCode: '+98' },
  { code: '0964', flag: 'https://flagcdn.com/iq.svg', name: 'Iraq', dialCode: '+964' },
  { code: '0353', flag: 'https://flagcdn.com/ie.svg', name: 'Ireland', dialCode: '+353' },
  { code: '0444', flag: 'https://flagcdn.com/im.svg', name: 'Isle of Man', dialCode: '+44' },
  { code: '0972', flag: 'https://flagcdn.com/il.svg', name: 'Israel', dialCode: '+972' },
  { code: '0039', flag: 'https://flagcdn.com/it.svg', name: 'Italy', dialCode: '+39' },
  { code: '1876', flag: 'https://flagcdn.com/jm.svg', name: 'Jamaica', dialCode: '+1876' },
  { code: '0081', flag: 'https://flagcdn.com/jp.svg', name: 'Japan', dialCode: '+81' },

  { code: '0962', flag: 'https://flagcdn.com/jo.svg', name: 'Jordan', dialCode: '+962' },
  { code: '0076', flag: 'https://flagcdn.com/kz.svg', name: 'Kazakhstan', dialCode: '+7' },
  { code: '0254', flag: 'https://flagcdn.com/ke.svg', name: 'Kenya', dialCode: '+254' },
  { code: '0686', flag: 'https://flagcdn.com/ki.svg', name: 'Kiribati', dialCode: '+686' },
  { code: '0965', flag: 'https://flagcdn.com/kw.svg', name: 'Kuwait', dialCode: '+965' },
  { code: '0996', flag: 'https://flagcdn.com/kg.svg', name: 'Kyrgyzstan', dialCode: '+996' },
  { code: '0856', flag: 'https://flagcdn.com/la.svg', name: 'Laos', dialCode: '+856' },
  { code: '0371', flag: 'https://flagcdn.com/lv.svg', name: 'Latvia', dialCode: '+371' },
  { code: '0961', flag: 'https://flagcdn.com/lb.svg', name: 'Lebanon', dialCode: '+961' },
  { code: '0266', flag: 'https://flagcdn.com/ls.svg', name: 'Lesotho', dialCode: '+266' },
  { code: '0231', flag: 'https://flagcdn.com/lr.svg', name: 'Liberia', dialCode: '+231' },
  { code: '0218', flag: 'https://flagcdn.com/ly.svg', name: 'Libya', dialCode: '+218' },
  { code: '0423', flag: 'https://flagcdn.com/li.svg', name: 'Liechtenstein', dialCode: '+423' },
  { code: '0370', flag: 'https://flagcdn.com/lt.svg', name: 'Lithuania', dialCode: '+370' },
  { code: '0352', flag: 'https://flagcdn.com/lu.svg', name: 'Luxembourg', dialCode: '+352' },
  { code: '0853', flag: 'https://flagcdn.com/mo.svg', name: 'Macau', dialCode: '+853' },
  { code: '0389', flag: 'https://flagcdn.com/mk.svg', name: 'Macedonia', dialCode: '+389' },
  { code: '0261', flag: 'https://flagcdn.com/mg.svg', name: 'Madagascar', dialCode: '+261' },
  { code: '0265', flag: 'https://flagcdn.com/mw.svg', name: 'Malawi', dialCode: '+265' },
  { code: '0060', flag: 'https://flagcdn.com/my.svg', name: 'Malaysia', dialCode: '+60' },
  { code: '0960', flag: 'https://flagcdn.com/mv.svg', name: 'Maldives', dialCode: '+960' },
  { code: '0223', flag: 'https://flagcdn.com/ml.svg', name: 'Mali', dialCode: '+223' },
  { code: '0356', flag: 'https://flagcdn.com/mt.svg', name: 'Malta', dialCode: '+356' },
  { code: '0692', flag: 'https://flagcdn.com/mh.svg', name: 'Marshall Islands', dialCode: '+692' },
  { code: '0596', flag: 'https://flagcdn.com/mq.svg', name: 'Martinique', dialCode: '+596' },
  { code: '0222', flag: 'https://flagcdn.com/mr.svg', name: 'Mauritania', dialCode: '+222' },
  { code: '0230', flag: 'https://flagcdn.com/mu.svg', name: 'Mauritius', dialCode: '+230' },
  { code: '0262', flag: 'https://flagcdn.com/yt.svg', name: 'Mayotte', dialCode: '+262' },
  { code: '0052', flag: 'https://flagcdn.com/mx.svg', name: 'Mexico', dialCode: '+52' },
  { code: '0691', flag: 'https://flagcdn.com/fm.svg', name: 'Micronesia', dialCode: '+691' },
  { code: '0373', flag: 'https://flagcdn.com/md.svg', name: 'Moldova', dialCode: '+373' },
  { code: '0377', flag: 'https://flagcdn.com/mc.svg', name: 'Monaco', dialCode: '+377' },
  { code: '0976', flag: 'https://flagcdn.com/mn.svg', name: 'Mongolia', dialCode: '+976' },
  { code: '0382', flag: 'https://flagcdn.com/me.svg', name: 'Montenegro', dialCode: '+382' },
  { code: '1664', flag: 'https://flagcdn.com/ms.svg', name: 'Montserrat', dialCode: '+1664' },
  { code: '0212', flag: 'https://flagcdn.com/ma.svg', name: 'Morocco', dialCode: '+212' },
  { code: '0258', flag: 'https://flagcdn.com/mz.svg', name: 'Mozambique', dialCode: '+258' },
  { code: '0095', flag: 'https://flagcdn.com/mm.svg', name: 'Myanmar', dialCode: '+95' },
  { code: '0264', flag: 'https://flagcdn.com/na.svg', name: 'Namibia', dialCode: '+264' },
  { code: '0674', flag: 'https://flagcdn.com/nr.svg', name: 'Nauru', dialCode: '+674' },
  { code: '0977', flag: 'https://flagcdn.com/np.svg', name: 'Nepal', dialCode: '+977' },
  { code: '0031', flag: 'https://flagcdn.com/nl.svg', name: 'Netherlands', dialCode: '+31' },
  { code: '0599', flag: 'https://flagcdn.com/an.svg', name: 'Netherlands Antilles', dialCode: '+599' },
  { code: '0687', flag: 'https://flagcdn.com/nc.svg', name: 'New Caledonia', dialCode: '+687' },
  { code: '0064', flag: 'https://flagcdn.com/nz.svg', name: 'New Zealand', dialCode: '+64' },
  { code: '0505', flag: 'https://flagcdn.com/ni.svg', name: 'Nicaragua', dialCode: '+505' },
  { code: '0227', flag: 'https://flagcdn.com/ne.svg', name: 'Niger', dialCode: '+227' },
  { code: '0234', flag: 'https://flagcdn.com/ng.svg', name: 'Nigeria', dialCode: '+234' },
  { code: '0683', flag: 'https://flagcdn.com/nu.svg', name: 'Niue', dialCode: '+683' },
  { code: '0672', flag: 'https://flagcdn.com/nf.svg', name: 'Norfolk Island', dialCode: '+672' },
  { code: '0850', flag: 'https://flagcdn.com/kp.svg', name: 'North Korea', dialCode: '+850' },
  { code: '1670', flag: 'https://flagcdn.com/mp.svg', name: 'Northern Mariana Islands', dialCode: '+1670' },
  { code: '0047', flag: 'https://flagcdn.com/no.svg', name: 'Norway', dialCode: '+47' },
  { code: '0968', flag: 'https://flagcdn.com/om.svg', name: 'Oman', dialCode: '+968' },
  { code: '0092', flag: 'https://flagcdn.com/pk.svg', name: 'Pakistan', dialCode: '+92' },
  { code: '0680', flag: 'https://flagcdn.com/pw.svg', name: 'Palau', dialCode: '+680' },
  { code: '0970', flag: 'https://flagcdn.com/ps.svg', name: 'Palestine', dialCode: '+970' },
  { code: '0507', flag: 'https://flagcdn.com/pa.svg', name: 'Panama', dialCode: '+507' },
  { code: '0675', flag: 'https://flagcdn.com/pg.svg', name: 'Papua New Guinea', dialCode: '+675' },
  { code: '0595', flag: 'https://flagcdn.com/py.svg', name: 'Paraguay', dialCode: '+595' },
  { code: '0051', flag: 'https://flagcdn.com/pe.svg', name: 'Peru', dialCode: '+51' },
  { code: '0063', flag: 'https://flagcdn.com/ph.svg', name: 'Philippines', dialCode: '+63' },

  { code: '0048', flag: 'https://flagcdn.com/pl.svg', name: 'Poland', dialCode: '+48' },
  { code: '0351', flag: 'https://flagcdn.com/pt.svg', name: 'Portugal', dialCode: '+351' },
  { code: '1787', flag: 'https://flagcdn.com/pr.svg', name: 'Puerto Rico', dialCode: '+1787' },
  { code: '0974', flag: 'https://flagcdn.com/qa.svg', name: 'Qatar', dialCode: '+974' },
  { code: '0242', flag: 'https://flagcdn.com/re.svg', name: 'Reunion', dialCode: '+242' },
  { code: '0040', flag: 'https://flagcdn.com/ro.svg', name: 'Romania', dialCode: '+40' },
  { code: '0070', flag: 'https://flagcdn.com/ru.svg', name: 'Russia', dialCode: '+7' },
  { code: '0250', flag: 'https://flagcdn.com/rw.svg', name: 'Rwanda', dialCode: '+250' },
  { code: '0590', flag: 'https://flagcdn.com/bl.svg', name: 'Saint Barthélemy', dialCode: '+590' },
  { code: '0290', flag: 'https://flagcdn.com/sh.svg', name: 'Saint Helena', dialCode: '+290' },
  { code: '1869', flag: 'https://flagcdn.com/kn.svg', name: 'Saint Kitts and Nevis', dialCode: '+1869' },
  { code: '1758', flag: 'https://flagcdn.com/lc.svg', name: 'Saint Lucia', dialCode: '+1758' },
 
  { code: '0508', flag: 'https://flagcdn.com/pm.svg', name: 'Saint Pierre and Miquelon', dialCode: '+508' },
  { code: '1784', flag: 'https://flagcdn.com/vc.svg', name: 'Saint Vincent and the Grenadines', dialCode: '+1784' },
  { code: '0685', flag: 'https://flagcdn.com/ws.svg', name: 'Samoa', dialCode: '+685' },
  { code: '0378', flag: 'https://flagcdn.com/sm.svg', name: 'San Marino', dialCode: '+378' },
  { code: '0239', flag: 'https://flagcdn.com/st.svg', name: 'Sao Tome and Principe', dialCode: '+239' },
  { code: '0966', flag: 'https://flagcdn.com/sa.svg', name: 'Saudi Arabia', dialCode: '+966' },
  { code: '0221', flag: 'https://flagcdn.com/sn.svg', name: 'Senegal', dialCode: '+221' },
  { code: '0381', flag: 'https://flagcdn.com/rs.svg', name: 'Serbia', dialCode: '+381' },
  { code: '0248', flag: 'https://flagcdn.com/sc.svg', name: 'Seychelles', dialCode: '+248' },
  { code: '0232', flag: 'https://flagcdn.com/sl.svg', name: 'Sierra Leone', dialCode: '+232' },
  { code: '0065', flag: 'https://flagcdn.com/sg.svg', name: 'Singapore', dialCode: '+65' },
  { code: '1721', flag: 'https://flagcdn.com/sx.svg', name: 'Sint Maarten', dialCode: '+1721' },
  { code: '0421', flag: 'https://flagcdn.com/sk.svg', name: 'Slovakia', dialCode: '+421' },
  { code: '0386', flag: 'https://flagcdn.com/si.svg', name: 'Slovenia', dialCode: '+386' },
  { code: '0677', flag: 'https://flagcdn.com/sb.svg', name: 'Solomon Islands', dialCode: '+677' },
  { code: '0252', flag: 'https://flagcdn.com/so.svg', name: 'Somalia', dialCode: '+252' },
  { code: '0027', flag: 'https://flagcdn.com/za.svg', name: 'South Africa', dialCode: '+27' },
  { code: '0082', flag: 'https://flagcdn.com/kr.svg', name: 'South Korea', dialCode: '+82' },
  { code: '0211', flag: 'https://flagcdn.com/ss.svg', name: 'South Sudan', dialCode: '+211' },
  { code: '0034', flag: 'https://flagcdn.com/es.svg', name: 'Spain', dialCode: '+34' },
  { code: '0094', flag: 'https://flagcdn.com/lk.svg', name: 'Sri Lanka', dialCode: '+94' },
  { code: '0249', flag: 'https://flagcdn.com/sd.svg', name: 'Sudan', dialCode: '+249' },
  { code: '0597', flag: 'https://flagcdn.com/sr.svg', name: 'Suriname', dialCode: '+597' },
  
  { code: '0268', flag: 'https://flagcdn.com/sz.svg', name: 'Swaziland', dialCode: '+268' },
  { code: '0046', flag: 'https://flagcdn.com/se.svg', name: 'Sweden', dialCode: '+46' },
  { code: '0041', flag: 'https://flagcdn.com/ch.svg', name: 'Switzerland', dialCode: '+41' },
  { code: '0963', flag: 'https://flagcdn.com/sy.svg', name: 'Syria', dialCode: '+963' },
  { code: '0886', flag: 'https://flagcdn.com/tw.svg', name: 'Taiwan', dialCode: '+886' },
  { code: '0992', flag: 'https://flagcdn.com/tj.svg', name: 'Tajikistan', dialCode: '+992' },
  { code: '0255', flag: 'https://flagcdn.com/tz.svg', name: 'Tanzania', dialCode: '+255' },
  { code: '0066', flag: 'https://flagcdn.com/th.svg', name: 'Thailand', dialCode: '+66' },

  { code: '0228', flag: 'https://flagcdn.com/tg.svg', name: 'Togo', dialCode: '+228' },
  { code: '0690', flag: 'https://flagcdn.com/tk.svg', name: 'Tokelau', dialCode: '+690' },
  { code: '0676', flag: 'https://flagcdn.com/to.svg', name: 'Tonga', dialCode: '+676' },
  { code: '1868', flag: 'https://flagcdn.com/tt.svg', name: 'Trinidad and Tobago', dialCode: '+1868' },
  { code: '0216', flag: 'https://flagcdn.com/tn.svg', name: 'Tunisia', dialCode: '+216' },
  { code: '0090', flag: 'https://flagcdn.com/tr.svg', name: 'Turkey', dialCode: '+90' },
  { code: '0993', flag: 'https://flagcdn.com/tm.svg', name: 'Turkmenistan', dialCode: '+993' },
  { code: '1649', flag: 'https://flagcdn.com/tc.svg', name: 'Turks and Caicos Islands', dialCode: '+1649' },
  { code: '0688', flag: 'https://flagcdn.com/tv.svg', name: 'Tuvalu', dialCode: '+688' },
  { code: '1340', flag: 'https://flagcdn.com/vi.svg', name: 'U.S. Virgin Islands', dialCode: '+1340' },
  { code: '0256', flag: 'https://flagcdn.com/ug.svg', name: 'Uganda', dialCode: '+256' },
  { code: '0380', flag: 'https://flagcdn.com/ua.svg', name: 'Ukraine', dialCode: '+380' },
  { code: '0971', flag: 'https://flagcdn.com/ae.svg', name: 'United Arab Emirates', dialCode: '+971' },
  { code: '0044', flag: 'https://flagcdn.com/gb.svg', name: 'United Kingdom', dialCode: '+44' },
  { code: '001', flag: 'https://flagcdn.com/us.svg', name: 'United States', dialCode: '+1' },
  { code: '0598', flag: 'https://flagcdn.com/uy.svg', name: 'Uruguay', dialCode: '+598' },
  { code: '0998', flag: 'https://flagcdn.com/uz.svg', name: 'Uzbekistan', dialCode: '+998' },
  { code: '0678', flag: 'https://flagcdn.com/vu.svg', name: 'Vanuatu', dialCode: '+678' },
  { code: '0379', flag: 'https://flagcdn.com/va.svg', name: 'Vatican', dialCode: '+379' },
  { code: '0058', flag: 'https://flagcdn.com/ve.svg', name: 'Venezuela', dialCode: '+58' },
  { code: '0084', flag: 'https://flagcdn.com/vn.svg', name: 'Vietnam', dialCode: '+84' },
  { code: '0681', flag: 'https://flagcdn.com/wf.svg', name: 'Wallis and Futuna', dialCode: '+681' },
  { code: '0967', flag: 'https://flagcdn.com/ye.svg', name: 'Yemen', dialCode: '+967' },
  { code: '0260', flag: 'https://flagcdn.com/zm.svg', name: 'Zambia', dialCode: '+260' },
  { code: '0263', flag: 'https://flagcdn.com/zw.svg', name: 'Zimbabwe', dialCode: '+263' }
].sort((a, b) => a.name.localeCompare(b.name));